// Generated by Skyramp v1.3.30 on 2026-07-07 19:05:17.271453687 +0000 UTC m=+497.942456873
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output logs-no-stream-quick-pick-more-streams-count.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Logs \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/logs_no_stream_quick_pick_more_streams_count_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/logs?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();

    await expect(page.getByRole('button', { name: /^(access_logs|app_logs|quickpick_stream_[1-6])$/ })).toHaveCount(8);
    await expect(page.locator('[data-test="logs-search-stream-quick-pick-more"]')).toHaveText('Search above for 3 more');
    await expect(page.getByRole('button', { name: 'quickpick_stream_7', exact: true })).not.toBeVisible();
    await expect(page.getByRole('button', { name: 'quickpick_stream_8', exact: true })).not.toBeVisible();
    await expect(page.getByRole('heading', { name: 'Pick a stream to start exploring' })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
