// Generated by Skyramp v1.3.30 on 2026-07-07 19:05:15.713559654 +0000 UTC m=+496.384562851
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output logs-no-stream-quick-pick-select.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Logs \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/logs_no_stream_quick_pick_select_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(536000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:5080/web/logs?org_identifier=default");
    await page.waitForLoadState('networkidle');
    await page.getByRole('heading', { name: 'Pick a stream to start exploring' }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole('heading', { name: 'Pick a stream to start exploring' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'access_logs', exact: true })).toBeVisible();
    await page.locator("[data-test=\"logs-search-stream-quick-pick-test_stream\"]").click();
    await expect(page.getByRole('button', { name: 'test_stream', exact: true })).toHaveText('test_stream');
    await expect(page.getByRole('heading', { name: 'Pick a stream to start exploring' })).not.toBeVisible();
    await expect(page.getByRole('button', { name: 'access_logs', exact: true })).not.toBeVisible();
    await expect(page.getByRole('heading', { name: 'Run a query to see results' })).toHaveText('Run a query to see results');
    await expect(page.getByRole('button', { name: 'level', exact: true })).toHaveText('level');
    await expect(page.getByRole('button', { name: 'message', exact: true })).toHaveText('message');
    await expect(page.getByRole('button', { name: 'service', exact: true })).toHaveText('service');

    expect(pageErrors).toHaveLength(0);
});
