// Generated by Skyramp v1.3.30 on 2026-07-07 19:25:37.170235536 +0000 UTC m=+1128.809263083
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output metrics-deep-link-override.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Metrics \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/metrics_deep_link_override_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(519000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/metrics?org_identifier=default&chart_type=bar&query_type=promql&stream_name=http_requests_total&query=aHR0cF9yZXF1ZXN0c190b3RhbHttZXRob2Q9IkdFVCJ9");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();

    await expect(page.locator("[data-test=\"index-dropdown-stream-trigger\"]")).toContainText("http_requests_total");
    await expect(page.locator("#dashboard-query-editor-promql")).toContainText("http_requests_total{method=\"GET\"}");
    await expect(page.locator("[data-test=\"dashboard-custom-query-type\"]")).toHaveAttribute("aria-pressed", "true");

    expect(pageErrors).toHaveLength(0);
});
