# Generated by Skyramp v1.3.30 on 2026-07-07 07:27:28.737647303 +0000 UTC m=+229.234918623
# Command: skyramp generate contract rest http://localhost:5080/healthz \
# 		--api-schema http://localhost:5080/api-doc/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output healthz_service_field_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /healthz GET
def test_healthz_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_healthz_GET_response_body = r'''{
        "status": "ok",
        "service": "openobserve"
    }'''

    # Execute Request
    healthz_GET_response = client.send_request(
        url=URL,
        path="/healthz",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert healthz_GET_response.status_code == 200
    assert skyramp.check_schema(healthz_GET_response, expected_healthz_GET_response_body)
    assert skyramp.get_response_value(healthz_GET_response, "status") is not None
    assert skyramp.get_response_value(healthz_GET_response, "status") == "ok"
    assert skyramp.get_response_value(healthz_GET_response, "service") == "openobserve"


if __name__ == "__main__":
    test_healthz_get()
