# Generated by Skyramp v1.3.30 on 2026-07-07 20:18:15.319890896 +0000 UTC m=+701.965894099
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output ingestion_tokens_enable_disable_forbidden_for_viewer_role_integration_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/openobserve/openobserve/tests/scenario_ingestion_tokens_enable_disable_forbidden_for_viewer_role.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    ingestion_tokens = "skytoken_enable2_070726"

    # Request Body
    # NOTE: POST /api/{org_id}/users unconditionally forces every created user
    # to Admin role in OSS builds (see save() in handler/http/request/users/mod.rs,
    # which sets `user.role.base_role = UserRole::Admin` regardless of the
    # requested role under #[cfg(not(feature = "enterprise"))]). That makes it
    # impossible to provision a genuinely non-admin/root identity through that
    # endpoint. POST /api/{org_id}/service_accounts does not apply that
    # override -- it always creates a ServiceAccount-role identity -- so it is
    # used here to exercise the new non-admin/root guard.
    users_POST_request_body = r'''{
        "email": "skyramp_viewer2v3_070726@test.invalid",
        "first_name": "skyramp",
        "last_name": "viewer2"
    }'''

    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/service_accounts",
        method="POST",
        body=users_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert users_POST_response.status_code == 200
    assert skyramp.get_response_value(users_POST_response, "message") == "User saved successfully"
    assert skyramp.get_response_value(users_POST_response, "code") == 200
    assert skyramp.get_response_value(users_POST_response, "user") == "skyramp_viewer2v3_070726@test.invalid"
    viewer_token = skyramp.get_response_value(users_POST_response, "token")
    assert viewer_token, "service account token should be non-empty"

    # Request Body
    ingestion_tokens_POST_request_body = r'''{
        "description": "skyramp baseline enable",
        "name": "skytoken_enable2_070726"
    }'''

    # Execute Request
    ingestion_tokens_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/ingestion-tokens",
        method="POST",
        body=ingestion_tokens_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert ingestion_tokens_POST_response.status_code == 200
    assert skyramp.get_response_value(ingestion_tokens_POST_response, "data.name") == "skytoken_enable2_070726"
    assert skyramp.get_response_value(ingestion_tokens_POST_response, "data.description") == "skyramp baseline enable"
    assert skyramp.get_response_value(ingestion_tokens_POST_response, "data.enabled") == True

    # Request Body
    ingestion_tokens_ingestion_tokens_PATCH_request_body = r'''{
        "enabled": false
    }'''

    # Execute Request
    ingestion_tokens_ingestion_tokens_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/default/ingestion-tokens/{ingestion-tokens}",
        method="PATCH",
        body=ingestion_tokens_ingestion_tokens_PATCH_request_body,
        headers=headers,
        path_params={"ingestion-tokens": ingestion_tokens}
    )

    # Generated Assertions
    assert ingestion_tokens_ingestion_tokens_PATCH_response.status_code == 200
    assert skyramp.get_response_value(ingestion_tokens_ingestion_tokens_PATCH_response, "message") == '{"message":"Token disabled successfully"}'

    # A service_account (non-admin/root) role must be forbidden from
    # enabling/disabling ingestion tokens (Admin/Root required). Auth uses the
    # generated token, not the password sent at creation time.
    import base64
    viewer_auth = base64.b64encode(f"skyramp_viewer2v3_070726@test.invalid:{viewer_token}".encode()).decode()
    viewer_headers = {"Authorization": "Basic " + viewer_auth}

    viewer_ingestion_tokens_PATCH_request_body = r'''{
        "enabled": true
    }'''

    viewer_ingestion_tokens_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/default/ingestion-tokens/{ingestion-tokens}",
        method="PATCH",
        body=viewer_ingestion_tokens_PATCH_request_body,
        headers=viewer_headers,
        path_params={"ingestion-tokens": ingestion_tokens}
    )

    # Generated Assertions
    assert viewer_ingestion_tokens_PATCH_response.status_code == 403
    assert skyramp.get_response_value(viewer_ingestion_tokens_PATCH_response, "message") == "Admin or Root role required to manage ingestion tokens"
    assert skyramp.get_response_value(viewer_ingestion_tokens_PATCH_response, "code") == 403


if __name__ == "__main__":
    test_integration()
