# Generated by Skyramp v1.3.30 on 2026-07-07 20:18:22.682631949 +0000 UTC m=+709.328635172
# Command: skyramp generate contract rest http://localhost:5080/api/default/ingestion-tokens/{name} \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output ingestion_tokens_enable_no_auth_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--path-params name=skytoken_noauth_070726 \
# 		--provider \
# 		--request-data {"enabled":false} \
# 		--response-status-code 401 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/ingestion-tokens/{name} PATCH
def test_ingestion_tokens_name_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    name = "skytoken_noauth_070726"

    # Request Body
    ingestion_tokens_name_PATCH_request_body = r'''{
        "enabled": false
    }'''

    # Execute Request
    ingestion_tokens_name_PATCH_response = client.send_request(
        url=URL,
        path="/api/default/ingestion-tokens/{name}",
        method="PATCH",
        body=ingestion_tokens_name_PATCH_request_body,
        headers=headers,
        path_params={"name": name}
    )

    # Generated Assertions
    assert ingestion_tokens_name_PATCH_response.status_code == 401


if __name__ == "__main__":
    test_ingestion_tokens_name_patch()
