# Generated by Skyramp v1.3.30 on 2026-07-07 20:18:18.226143458 +0000 UTC m=+704.872146671
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output ingestion_tokens_list_visible_to_org_admin_integration_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/openobserve/openobserve/tests/scenario_ingestion_tokens_list_visible_to_org_admin.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    ingestion_tokens_POST_request_body = r'''{
        "description": "skyramp cross-admin visibility",
        "name": "skytoken_vis2_070726"
    }'''

    # Execute Request
    ingestion_tokens_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/ingestion-tokens",
        method="POST",
        body=ingestion_tokens_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert ingestion_tokens_POST_response.status_code == 200
    assert skyramp.get_response_value(ingestion_tokens_POST_response, "data.name") == "skytoken_vis2_070726"
    assert skyramp.get_response_value(ingestion_tokens_POST_response, "data.description") == "skyramp cross-admin visibility"
    assert skyramp.get_response_value(ingestion_tokens_POST_response, "data.created_by") == "root@example.com"

    # Request Body
    users_POST_request_body = r'''{
        "email": "skyramp_admin2_070726@test.invalid",
        "password": "Testpass#123",
        "role": "admin"
    }'''

    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert users_POST_response.status_code == 200
    assert skyramp.get_response_value(users_POST_response, "message") == "User saved successfully"
    assert skyramp.get_response_value(users_POST_response, "code") == 200

    # Admin (non-root, not the token's creator) must still be allowed to list ingestion
    # tokens, and must see the root-created token — org tokens are org-scoped, not
    # creator-scoped.
    import base64
    admin_auth = base64.b64encode(b"skyramp_admin2_070726@test.invalid:Testpass#123").decode()
    admin_headers = {"Authorization": "Basic " + admin_auth}

    admin_ingestion_tokens_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/default/ingestion-tokens",
        method="GET",
        headers=admin_headers
    )

    # Generated Assertions
    assert admin_ingestion_tokens_GET_response.status_code == 200
    found_index = None
    idx = 0
    while True:
        name_at_idx = skyramp.get_response_value(admin_ingestion_tokens_GET_response, f"data.{idx}.name")
        if name_at_idx is None:
            break
        if name_at_idx == "skytoken_vis2_070726":
            found_index = idx
            break
        idx += 1
    assert found_index is not None, \
        "admin should see the root-created token 'skytoken_vis2_070726' in the list"
    assert skyramp.get_response_value(admin_ingestion_tokens_GET_response, f"data.{found_index}.description") == "skyramp cross-admin visibility"
    assert skyramp.get_response_value(admin_ingestion_tokens_GET_response, f"data.{found_index}.created_by") == "root@example.com"
    assert skyramp.get_response_value(admin_ingestion_tokens_GET_response, f"data.{found_index}.enabled") == True


if __name__ == "__main__":
    test_integration()
