# Generated by Skyramp v1.3.30 on 2026-07-07 20:18:20.049971916 +0000 UTC m=+706.695975109
# Command: skyramp generate contract rest http://localhost:5080/api/default/ingestion-tokens \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output ingestion_tokens_list_no_auth_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/ingestion-tokens GET
def test_ingestion_tokens_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    ingestion_tokens_GET_response = client.send_request(
        url=URL,
        path="/api/default/ingestion-tokens",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert ingestion_tokens_GET_response.status_code == 401


if __name__ == "__main__":
    test_ingestion_tokens_get()
