# Generated by Skyramp v1.3.30 on 2026-07-07 07:28:26.751317826 +0000 UTC m=+287.248589146
# Command: skyramp generate contract rest http://localhost:5080/metrics \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output metrics_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /metrics GET
def test_metrics_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    metrics_GET_response = client.send_request(
        url=URL,
        path="/metrics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert metrics_GET_response.status_code == 200


if __name__ == "__main__":
    test_metrics_get()
