# Generated by Skyramp v1.3.30 on 2026-07-07 07:27:31.306911299 +0000 UTC m=+231.804182619
# Command: skyramp generate contract rest http://localhost:5080/schedulez \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output schedulez_service_field_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /schedulez GET
def test_schedulez_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    schedulez_GET_response = client.send_request(
        url=URL,
        path="/schedulez",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert schedulez_GET_response.status_code == 200
    assert skyramp.get_response_value(schedulez_GET_response, "status") == "ok"
    assert skyramp.get_response_value(schedulez_GET_response, "service") == "openobserve"


if __name__ == "__main__":
    test_schedulez_get()
