# Generated by Skyramp v1.3.30 on 2026-07-07 20:25:03.405539585 +0000 UTC m=+714.956789646
# Command: skyramp generate contract rest http://localhost:5080/api/{org_id}/short/{short_id} \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output short_url_retrieve_nonexistent_404_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--path-params org_id=default,short_id=skyrampnonexist9a \
# 		--provider \
# 		--query-params type=ui \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/{org_id}/short/{short_id} GET
def test_short_short_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    org_id = "default"
    short_id = "skyrampnonexist9a"

    # Execute Request
    short_short_id_GET_response = client.send_request(
        url=URL,
        path="/api/{org_id}/short/{short_id}",
        method="GET",
        headers=headers,
        path_params={
            "org_id": org_id,
            "short_id": short_id
        },
        query_params={"type": "ui"}
    )

    # Generated Assertions
    assert short_short_id_GET_response.status_code == 404


if __name__ == "__main__":
    test_short_short_id_get()
