# Generated by Skyramp v1.3.30 on 2026-07-07 20:25:24.385722383 +0000 UTC m=+735.936972464
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output short_url_idempotent_reuse_integration_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/openobserve/openobserve/tests/scenario_short_url_idempotent_reuse.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    short_POST_request_body = r'''{
        "original_url": "https://skyramp-idem-1783455803.example.com/reuse"
    }'''

    # Execute Request
    short_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/short",
        method="POST",
        body=short_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert short_POST_response.status_code == 200
    assert skyramp.get_response_value(short_POST_response, "short_url") == "http://localhost:5080/web/short/9944b90949a51a6f?org_identifier=default"

    # Request Body
    short_POST_1_request_body = r'''{
        "original_url": "https://skyramp-idem-1783455803.example.com/reuse"
    }'''

    # Execute Request
    short_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/default/short",
        method="POST",
        body=short_POST_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert short_POST_1_response.status_code == 200
    assert skyramp.get_response_value(short_POST_1_response, "short_url") == skyramp.get_response_value(short_POST_response, "short_url")


if __name__ == "__main__":
    test_integration()
