# Generated by Skyramp v1.3.30 on 2026-07-07 20:25:15.867169618 +0000 UTC m=+727.418419699
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--chaining-key identifier \
# 		--framework pytest \
# 		--language python \
# 		--output short_url_cross_org_collision_integration_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/openobserve/openobserve/tests/scenario_short_url_cross_org_collision.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    organizations_POST_request_body = r'''{
        "name": "skyramp bugcheck 1783455803"
    }'''

    # Execute Request
    organizations_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/organizations",
        method="POST",
        body=organizations_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert organizations_POST_response.status_code == 200
    assert skyramp.get_response_value(organizations_POST_response, "name") == "skyramp bugcheck 1783455803"
    assert skyramp.get_response_value(organizations_POST_response, "org_type") == "custom"
    api = skyramp.get_response_value(organizations_POST_response, "identifier")
    assert api is not None

    # Request Body
    short_POST_request_body = r'''{
        "original_url": "https://skyramp-bug-1783455803.example.com/collision"
    }'''

    # Execute Request
    short_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/short",
        method="POST",
        body=short_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert short_POST_response.status_code == 200
    assert "org_identifier=default" in skyramp.get_response_value(short_POST_response, "short_url")

    # Request Body
    api_short_POST_request_body = r'''{
        "original_url": "https://skyramp-bug-1783455803.example.com/collision"
    }'''

    # Execute Request
    api_short_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/{api}/short",
        method="POST",
        body=api_short_POST_request_body,
        headers=headers,
        path_params={"api": api}
    )

    # Generated Assertions
    assert api_short_POST_response.status_code == 200
    assert f"org_identifier={api}" in skyramp.get_response_value(api_short_POST_response, "short_url")


if __name__ == "__main__":
    test_integration()
