# Generated by Skyramp v1.3.30 on 2026-07-07 20:25:20.507816426 +0000 UTC m=+732.059066507
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--chaining-key identifier \
# 		--framework pytest \
# 		--language python \
# 		--output short_url_cross_org_isolation_integration_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/openobserve/openobserve/tests/scenario_short_url_cross_org_isolation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    type = "ui"

    # Request Body
    organizations_POST_request_body = r'''{
        "name": "skyramp crossorg 1783455803"
    }'''

    # Execute Request
    organizations_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/organizations",
        method="POST",
        body=organizations_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert organizations_POST_response.status_code == 200
    assert skyramp.get_response_value(organizations_POST_response, "name") == "skyramp crossorg 1783455803"
    assert skyramp.get_response_value(organizations_POST_response, "org_type") == "custom"
    api = skyramp.get_response_value(organizations_POST_response, "identifier")
    assert api is not None

    # Request Body
    short_POST_request_body = r'''{
        "original_url": "https://skyramp-cross-1783455803.example.com/isolation"
    }'''

    # Execute Request
    short_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/short",
        method="POST",
        body=short_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert short_POST_response.status_code == 200
    assert skyramp.get_response_value(short_POST_response, "short_url") == "http://localhost:5080/web/short/712a9d7cf16347a4?org_identifier=default"

    # Execute Request
    api_short_712a9d7cf16347a4_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/{api}/short/712a9d7cf16347a4",
        method="GET",
        headers=headers,
        path_params={"api": api},
        query_params={"type": [type]}
    )

    # Generated Assertions
    assert api_short_712a9d7cf16347a4_GET_response.status_code == 404

    # Execute Request
    short_712a9d7cf16347a4_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/default/short/712a9d7cf16347a4",
        method="GET",
        headers=headers,
        query_params={"type": [type]}
    )

    # Generated Assertions
    assert short_712a9d7cf16347a4_GET_response.status_code == 200
    assert skyramp.check_schema(short_712a9d7cf16347a4_GET_response, '"https://skyramp-cross-1783455803.example.com/isolation"')


if __name__ == "__main__":
    test_integration()
