# Generated by Skyramp v1.3.30 on 2026-07-07 20:25:10.064711942 +0000 UTC m=+721.615962013
# Command: skyramp generate contract rest http://localhost:5080/api/{org_id}/streams/{stream_name}/data_by_time_range/status/{id} \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output stream_delete_status_job_not_found_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--path-params org_id=default,stream_name=skyramp_test_stream,id=skyramp_nonexistent_job_id \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/{org_id}/streams/{stream_name}/data_by_time_range/status/{id} GET
def test_status_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "skyramp_nonexistent_job_id"
    org_id = "default"
    stream_name = "skyramp_test_stream"

    # Execute Request
    status_id_GET_response = client.send_request(
        url=URL,
        path="/api/{org_id}/streams/{stream_name}/data_by_time_range/status/{id}",
        method="GET",
        headers=headers,
        path_params={
            "id": id,
            "org_id": org_id,
            "stream_name": stream_name
        }
    )

    # Generated Assertions
    assert status_id_GET_response.status_code == 200
    assert skyramp.get_response_value(status_id_GET_response, "id") == id
    assert skyramp.get_response_value(status_id_GET_response, "status") == "Pending"
    assert skyramp.get_response_value(status_id_GET_response, "metadata.0") is None
    assert skyramp.get_response_value(status_id_GET_response, "errors.0.error") == "DbError# SeaORMError# job not found"
    assert skyramp.get_response_value(status_id_GET_response, "errors.1") is None


if __name__ == "__main__":
    test_status_id_get()
