# Generated by Skyramp v1.3.30 on 2026-07-07 17:52:51.324896782 +0000 UTC m=+557.880314473
# Command: skyramp generate contract rest http://localhost:5080/api/default/alerts/templates \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output templates_list_isprebuilt_field_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/alerts/templates GET
def test_templates_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    templates_GET_response = client.send_request(
        url=URL,
        path="/api/default/alerts/templates",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert templates_GET_response.status_code == 200
    assert skyramp.get_response_value(templates_GET_response, "0.name") == "prebuilt_discord"
    assert skyramp.get_response_value(templates_GET_response, "0.isPrebuilt") == True
    assert skyramp.get_response_value(templates_GET_response, "0.type") == "http"
    assert skyramp.get_response_value(templates_GET_response, "6.name") == "prebuilt_slack"
    assert skyramp.get_response_value(templates_GET_response, "6.isPrebuilt") == True
    assert skyramp.get_response_value(templates_GET_response, "6.type") == "http"
    assert skyramp.get_response_value(templates_GET_response, "1.name") == "prebuilt_email"
    assert skyramp.get_response_value(templates_GET_response, "1.isPrebuilt") == True
    assert skyramp.get_response_value(templates_GET_response, "1.type") == "email"
    assert skyramp.get_response_value(templates_GET_response, "1.title") == "OpenObserve Alert: {alert_name}"


if __name__ == "__main__":
    test_templates_get()
