# Generated by Skyramp v1.3.30 on 2026-07-07 17:52:46.151654597 +0000 UTC m=+552.707072297
# Command: skyramp generate contract rest http://localhost:5080/api/default/alerts/templates/prebuilt_slack \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output templates_edit_prebuilt_allowed_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"prebuilt_slack","body":"*Alert:* {alert_name}\n*Org:* {org_name}","type":"http"} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/alerts/templates/prebuilt_slack PUT
def test_prebuilt_slack_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    prebuilt_slack_PUT_request_body = r'''{
        "body": "*Alert:* {alert_name}\n*Org:* {org_name}",
        "name": "prebuilt_slack",
        "type": "http"
    }'''

    # Execute Request
    prebuilt_slack_PUT_response = client.send_request(
        url=URL,
        path="/api/default/alerts/templates/prebuilt_slack",
        method="PUT",
        body=prebuilt_slack_PUT_request_body,
        headers=headers
    )

    # Generated Assertions
    assert prebuilt_slack_PUT_response.status_code == 200
    assert skyramp.get_response_value(prebuilt_slack_PUT_response, "code") == 200
    assert skyramp.get_response_value(prebuilt_slack_PUT_response, "message") == "Template updated"


if __name__ == "__main__":
    test_prebuilt_slack_put()
