# Generated by Skyramp v1.3.30 on 2026-07-07 17:52:38.756982679 +0000 UTC m=+545.312400379
# Command: skyramp generate contract rest http://localhost:5080/api/default/alerts/templates \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output templates_create_reserved_name_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"prebuilt_slack","body":"test body {alert_name}","type":"http"} \
# 		--response-status-code 400 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/alerts/templates POST
def test_templates_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    templates_POST_request_body = r'''{
        "body": "test body {alert_name}",
        "name": "prebuilt_slack",
        "type": "http"
    }'''

    # Execute Request
    templates_POST_response = client.send_request(
        url=URL,
        path="/api/default/alerts/templates",
        method="POST",
        body=templates_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert templates_POST_response.status_code == 400
    assert skyramp.get_response_value(templates_POST_response, "code") == 400
    assert skyramp.get_response_value(templates_POST_response, "message") == "Template name 'prebuilt_slack' is reserved for system prebuilt templates. Pick a different name."


if __name__ == "__main__":
    test_templates_post()
