# Generated by Skyramp v1.3.30 on 2026-07-07 17:52:42.220968924 +0000 UTC m=+548.776386625
# Command: skyramp generate contract rest http://localhost:5080/api/default/alerts/templates/prebuilt_slack \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output templates_delete_prebuilt_forbidden_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 403 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/default/alerts/templates/prebuilt_slack DELETE
def test_prebuilt_slack_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    prebuilt_slack_DELETE_response = client.send_request(
        url=URL,
        path="/api/default/alerts/templates/prebuilt_slack",
        method="DELETE",
        headers=headers
    )

    # Generated Assertions
    assert prebuilt_slack_DELETE_response.status_code == 403
    assert skyramp.get_response_value(prebuilt_slack_DELETE_response, "code") == 403
    assert skyramp.get_response_value(prebuilt_slack_DELETE_response, "message") == "Template 'prebuilt_slack' is a system prebuilt template and cannot be modified or deleted. Create a copy with a different name to customize it."


if __name__ == "__main__":
    test_prebuilt_slack_delete()
