# Generated by Skyramp v1.3.30 on 2026-07-07 17:53:12.977227415 +0000 UTC m=+579.532645125
# Command: skyramp generate integration rest \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--output template_delete_blocked_while_referenced_integration_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/openobserve/openobserve/tests/scenario_template_delete_blocked_while_referenced_by_destination.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    name = "dest_webhook_pr12423_1"
    templates = "custom_tmpl_pr12423_1"

    # Request Body
    templates_POST_request_body = r'''{
        "body": "*Alert:* {alert_name}\n*Org:* {org_name}",
        "name": "custom_tmpl_pr12423_1",
        "type": "http"
    }'''

    # Execute Request
    templates_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/alerts/templates",
        method="POST",
        body=templates_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert templates_POST_response.status_code == 200
    assert skyramp.get_response_value(templates_POST_response, "code") == 200
    assert skyramp.get_response_value(templates_POST_response, "message") == "Template saved"

    # Request Body
    destinations_POST_request_body = r'''{
        "method": "post",
        "name": "dest_webhook_pr12423_1",
        "skip_tls_verify": false,
        "template": "custom_tmpl_pr12423_1",
        "type": "http",
        "url": "https://hooks.slack.com/services/T00/B00/XXXXXXXXXXXXXXXXXXXXXXXX"
    }'''

    # Execute Request
    destinations_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/default/alerts/destinations",
        method="POST",
        body=destinations_POST_request_body,
        headers=headers,
        data_override={"name": name}
    )

    # Generated Assertions
    assert destinations_POST_response.status_code == 200
    assert skyramp.get_response_value(destinations_POST_response, "code") == 200
    assert skyramp.get_response_value(destinations_POST_response, "message") == "Destination saved"
    assert skyramp.get_response_value(destinations_POST_response, "name") == name

    # Execute Request
    destinations_destinations_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/default/alerts/destinations/{destinations}",
        method="GET",
        headers=headers,
        path_params={"destinations": name}
    )

    # Generated Assertions
    assert destinations_destinations_GET_response.status_code == 200
    assert skyramp.get_response_value(destinations_destinations_GET_response, "name") == name
    assert skyramp.get_response_value(destinations_destinations_GET_response, "template") == templates
    assert skyramp.get_response_value(destinations_destinations_GET_response, "url") == "https://hooks.slack.com/services/T00/B00/XXXXXXXXXXXXXXXXXXXXXXXX"
    assert skyramp.get_response_value(destinations_destinations_GET_response, "method") == "post"
    assert skyramp.get_response_value(destinations_destinations_GET_response, "type") == "http"
    assert skyramp.get_response_value(destinations_destinations_GET_response, "skip_tls_verify") == False

    # Execute Request
    templates_templates_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/default/alerts/templates/{templates}",
        method="DELETE",
        headers=headers,
        path_params={"templates": templates}
    )

    # Generated Assertions
    assert templates_templates_DELETE_response.status_code == 409
    assert skyramp.get_response_value(templates_templates_DELETE_response, "code") == 409
    assert skyramp.get_response_value(templates_templates_DELETE_response, "message") == f"Template is in use for destination {name}"


if __name__ == "__main__":
    test_integration()
