# Generated by Skyramp v1.3.30 on 2026-07-07 20:24:51.170272948 +0000 UTC m=+702.721523029
# Command: skyramp generate contract rest http://localhost:5080/api/{org_id}/{stream_name}/_values \
# 		--api-schema http://localhost:5080/api-doc/openapi.json \
# 		--auth-type Basic \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output values_filter_column_validation_contract_test.py \
# 		--output-dir /home/runner/work/openobserve/openobserve/tests \
# 		--overwrite \
# 		--path-params org_id=default,stream_name=skyramp_contract_test_stream \
# 		--provider \
# 		--query-params type=logs,fields=kubernetes_container_name,filter=nonexistent_column_probe=1,size=10,from=0,start_time=1783452261814283,end_time=1783455861814283 \
# 		--response-status-code 400 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:5080")

# contract test for /api/{org_id}/{stream_name}/_values GET
def test__values_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Basic " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    org_id = "default"
    stream_name = "skyramp_contract_test_stream"

    # Expected Response Body
    expected__values_GET_response_body = r'''"null"'''

    # Execute Request
    _values_GET_response = client.send_request(
        url=URL,
        path="/api/{org_id}/{stream_name}/_values",
        method="GET",
        headers=headers,
        path_params={
            "org_id": org_id,
            "stream_name": stream_name
        },
        query_params={
            "end_time": "1783455861814283",
            "fields": "kubernetes_container_name",
            "filter": "nonexistent_column_probe",
            "from": "0",
            "size": "10",
            "start_time": "1783452261814283",
            "type": "logs"
        }
    )

    # Generated Assertions
    assert _values_GET_response.status_code == 400
    assert skyramp.get_response_value(_values_GET_response, "code") == 400
    assert skyramp.get_response_value(_values_GET_response, "message") in ("Unknown filter column", "Invalid filter format")


if __name__ == "__main__":
    test__values_get()
