// Generated by Skyramp v1.3.30 on 2026-07-07 18:03:26.553456847 +0000 UTC m=+1193.108874547
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output add_destination_custom_template_selection.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/add_destination_custom_template_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(158000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/settings/alert_destinations?action=add&org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"alert-destination-list-add-alert-btn\"]").click();
    await page.getByText("SlackSend notifications to").click();
    await page.locator("[data-test=\"add-destination-name-input-field\"]").fill("slack_dest_pr12423_2");
    await page.locator("[data-test=\"slack-webhook-url-input-field\"]").fill("https://hooks.slack.com/services/T00/B00/YYYYYYYYYYYYYYYYYYYYYYYY");
    await page.locator("[data-test=\"add-destination-prebuilt-template-select-trigger\"]").click();
    await page.getByRole("option", { name: "custom_tmpl_pr12423_1" }).click();
    await expect(page.locator("[data-test=\"add-destination-prebuilt-template-select-trigger\"]")).toHaveText("custom_tmpl_pr12423_1");

    const destinationPostResponsePromise = page.waitForResponse((resp) => resp.url().includes("/alerts/destinations") && resp.request().method() === "POST");
    await page.locator("[data-test=\"add-destination-submit-btn\"]").click();
    const destinationPostResponse = await destinationPostResponsePromise;
    expect(destinationPostResponse.status()).toBe(200);
    expect(destinationPostResponse.request().postData() ?? "").toContain("custom_tmpl_pr12423_1");
    const destinationPostBody = await destinationPostResponse.json();
    expect(destinationPostBody.name).toBe("slack_dest_pr12423_2");
    expect(destinationPostBody.message).toBe("Destination saved");

    await expect(page.getByRole("row", { name: /slack_dest_pr12423_2/ }).getByRole("cell", { name: "custom_tmpl_pr12423_1" })).toHaveText("custom_tmpl_pr12423_1");
    expect(pageErrors).toHaveLength(0);
});
