// Generated by Skyramp v1.3.30 on 2026-07-08 06:43:13.994690606 +0000 UTC m=+972.059457810
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output add_dashboard_validation.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/add_dashboard_validation_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(142000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/dashboards?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"dashboard-new\"]").click();

    // Submit with empty Name — Zod schema's name.min(1) must block save
    await page.locator("[data-test=\"o-dialog-primary-btn\"]").click();
    await expect(page.getByRole("alert").filter({ hasText: "Name is required" })).toBeVisible();

    const dashboardName = `Skyramp Test Dashboard ${Date.now()}`;
    await page.locator("[data-test=\"add-dashboard-name-field\"]").fill(dashboardName);
    await page.locator("[data-test=\"o-dialog-primary-btn\"]").click();
    await expect(page.getByRole("heading", { name: dashboardName })).toHaveText(dashboardName);

    await page.locator("[data-test=\"dashboard-back-btn\"]").click();
    await expect(page.getByText("Dashboards", { exact: true }).first()).toBeVisible();
    await expect(page.getByRole("cell", { name: dashboardName })).toHaveText(dashboardName);

    expect(pageErrors).toHaveLength(0);
});
