// Generated by Skyramp v1.3.30 on 2026-07-08 00:11:50.695311669 +0000 UTC m=+527.459803872
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dashboards_folder_default_selection.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/dashboards_folder_default_selection_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(102000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on("pageerror", (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:5080/web/dashboards?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await expect(page).toHaveURL(/[?&]folder=default(&|$)/);
    await expect(page.locator("[data-test=\"dashboard-folder-tab-default\"]")).toHaveAttribute("aria-selected", "true");
    await page.locator("[data-test=\"dashboard-folder-tab-7480412667153219584\"]").click();
    await expect(page.locator("body")).toContainText("1");
    await expect(page.locator("[data-test=\"dashboard-folder-tab-7480412667153219584\"]")).toHaveAttribute("aria-selected", "true");
    await page.locator("[data-test=\"dashboard-folder-tab-default\"]").click();
    await expect(page.locator("body")).toContainText("0");
    await expect(page).toHaveURL(/[?&]folder=default(&|$)/);
    await expect(page.locator("[data-test=\"dashboard-folder-tab-default\"]")).toHaveAttribute("aria-selected", "true");

    expect(pageErrors).toHaveLength(0);
});
