// Generated by Skyramp
// UI test: an explicit user column selection (adding "service" as a display
// column) is not clobbered by the FTS default-column system pick on a
// subsequent search. Covers the isFtsDefaultColumn guard added across
// useLogs/logsUtils/useStreamFields/IndexList/SearchResult in this PR.

import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    page.setDefaultTimeout(pageTimeout);
    page = newSkyrampPlaywrightPage(page);

    const streamName = `fts_override_persists_${Date.now()}`;
    const orgIdentifier = "default";
    const baseUrl = "http://localhost:5080";

    await page.context().request.post(`${baseUrl}/api/${orgIdentifier}/${streamName}/_json`, {
        headers: {
            Authorization: `Basic ${Buffer.from("root@example.com:Complexpass#123").toString("base64")}`,
            "Content-Type": "application/json",
        },
        data: [
            { level: "error", message: "Fresh retry message batch 3 payment failed", service: "payments" },
            { level: "error", message: "Fresh retry message batch 2 payment failed", service: "payments" },
            { level: "error", message: "Fresh retry message batch 1 payment failed", service: "payments" },
        ],
    });

    await page.goto(`${baseUrl}/web/login`);
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.waitForURL("**/web/**");
    await page.waitForLoadState("networkidle");

    await page.goto(`${baseUrl}/web/logs?org_identifier=${orgIdentifier}&stream=${streamName}&stream_type=logs&quick_mode=false`);
    await page.waitForSelector("text=events");

    // Auto-pick can race with stream field metadata on the very first search;
    // an explicit re-run guarantees the resolved state before the user acts.
    await page.locator("[data-test=\"logs-search-bar-refresh-btn\"]").click();
    await expect(page.locator("[data-test=\"log-search-result-table-th-message\"]")).toHaveText("message", { timeout: 15000 });

    // Explicit user action: add "service" as a display column.
    await page.locator("#thirdLevel").getByRole("button", { name: "service" }).click();
    await page.locator("[data-test=\"log-search-index-list-add-service-field-btn\"]").click();

    await expect(page.locator("[data-test=\"log-search-result-table-th-message\"]")).toHaveText("message");
    await expect(page.locator("[data-test=\"log-search-result-table-th-service\"]")).toHaveText("service");
    await expect(page.locator("[data-test=\"log-table-column-0-service\"]")).toHaveText("payments");

    // Re-run the search: the explicit selection must persist, not be reverted
    // to a single system-picked FTS default column.
    await page.locator("[data-test=\"logs-search-bar-refresh-btn\"]").click();

    await expect(page.locator("[data-test=\"log-search-result-table-th-message\"]")).toHaveText("message", { timeout: 15000 });
    await expect(page.locator("[data-test=\"log-search-result-table-th-service\"]")).toHaveText("service");
    await expect(page.locator("[data-test=\"log-table-column-0-message\"]")).toHaveText(/^Fresh retry message batch \d payment failed$/);
    await expect(page.locator("[data-test=\"log-table-column-0-service\"]")).toHaveText("payments");
});
