// Generated by Skyramp
// UI test: Logs page auto-selects an FTS default display column (e.g. "message")
// instead of the generic raw "source" column when the user has made no explicit
// column selection. Covers resolveDefaultColumns() in web/src/composables/useLogs.ts.

import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    page.setDefaultTimeout(pageTimeout);
    page = newSkyrampPlaywrightPage(page);

    const streamName = `fts_auto_select_${Date.now()}`;
    const orgIdentifier = "default";
    const baseUrl = "http://localhost:5080";

    await page.context().request.post(`${baseUrl}/api/${orgIdentifier}/${streamName}/_json`, {
        headers: {
            Authorization: `Basic ${Buffer.from("root@example.com:Complexpass#123").toString("base64")}`,
            "Content-Type": "application/json",
        },
        data: [
            { level: "error", message: "Fresh retry message batch 3 payment failed", service: "payments" },
            { level: "error", message: "Fresh retry message batch 2 payment failed", service: "payments" },
            { level: "error", message: "Fresh retry message batch 1 payment failed", service: "payments" },
        ],
    });

    await page.goto(`${baseUrl}/web/login`);
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.waitForURL("**/web/**");
    await page.waitForLoadState("networkidle");

    await page.goto(`${baseUrl}/web/logs?org_identifier=${orgIdentifier}&stream=${streamName}&stream_type=logs&quick_mode=false`);
    await page.waitForSelector("text=events");

    // Auto-pick can race with stream field metadata on the very first search;
    // an explicit re-run guarantees the resolved state for a deterministic assertion.
    await page.locator("[data-test=\"logs-search-bar-refresh-btn\"]").click();

    await expect(page.locator("[data-test=\"log-search-result-table-th-message\"]")).toHaveText("message", { timeout: 15000 });
    await expect(page.locator("[data-test=\"log-table-column-0-message\"]")).toHaveText(/^Fresh retry message batch \d payment failed$/);
    await expect(page.locator("[data-test=\"log-search-result-table-th-source\"]")).toHaveCount(0);
});
