// Generated by Skyramp v1.3.30 on 2026-07-08 06:50:02.857405082 +0000 UTC m=+1380.922172286
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output general_settings_validation.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/general_settings_validation_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(104000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/settings/general?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();

    // Submit with an empty Scrape Interval — Zod schema's required-number check must block save
    await page.locator("[data-test=\"general-settings-scrape-interval-field\"]").fill("");
    await page.locator("[data-test=\"dashboard-add-submit\"]").click();
    await expect(page.getByRole("alert").filter({ hasText: "Scrape interval is required" })).toBeVisible();

    await page.locator("[data-test=\"general-settings-scrape-interval-field\"]").fill("30");
    await page.locator("[data-test=\"dashboard-add-submit\"]").click();
    await expect(page.locator("[data-test=\"general-settings-scrape-interval-field\"]")).toHaveValue("30");

    expect(pageErrors).toHaveLength(0);
});
