// Generated by Skyramp v1.3.30 on 2026-07-08 06:41:02.708221467 +0000 UTC m=+840.772988691
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output getstarted_onboarding_validation.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/getstarted_onboarding_validation_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1207000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Trigger the first-time-login onboarding dialog (GetStarted.vue) on every navigation
    await page.addInitScript(() => localStorage.setItem("isFirstTimeLogin", "true"));

    await page.goto("http://localhost:5080/web");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.waitForLoadState('networkidle');

    await page.locator("[data-test=\"onboarding-get-started-hear-about-us-field\"]").fill("From a friend");
    await page.locator("[data-test=\"onboarding-get-started-where-do-you-work-field\"]").fill("Acme Corp");

    // Submit with the terms checkbox unchecked — Zod schema's isAgree.refine() must block submission
    await page.locator("[data-test=\"onboarding-get-started-submit-btn\"]").click();
    await expect(page.getByText("You must accept the terms to")).toContainText("You must accept the terms to continue");

    // Checking the box clears the validation error (submit-then-change revalidation)
    await page.getByRole("checkbox", { name: "I have read and agree with" }).click();
    await expect(page.getByRole("checkbox", { name: "I have read and agree with" })).toBeChecked();
    await expect(page.getByText("You must accept the terms to")).not.toBeVisible();

    await page.locator("[data-test=\"onboarding-get-started-submit-btn\"]").click();
});
