// Generated by Skyramp v1.3.30 on 2026-07-08 06:37:49.690889453 +0000 UTC m=+921.858947870
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ingestion-tokens-basic-auth-credential.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/ingestion_tokens_basic_auth_trace.zip

// Import of required libraries
import { test, checkRequestPayload, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('Ingestion token reveals ready-to-use Basic Authorization header', async ({ page }) => {
    test.setTimeout(966000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Token name is unique per run to avoid name collisions across test re-runs
    const tokenName = `testbot-basicauth-token-${Date.now()}`;
    // Deterministic Basic-auth prefix for this run: base64("<tokenName>:") — the
    // token secret suffix is server-generated and random, so only the name-derived
    // prefix is asserted.
    const expectedAuthPrefix = `Basic ${Buffer.from(`${tokenName}:`).toString('base64')}`;

    // Expected request payloads for network assertions
    const expectedPayload1 = {
        "description": "",
        "name": tokenName
    };

    await page.goto("http://localhost:5080/web/login");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();

    await page.goto("http://localhost:5080/web/iam/ingestionTokens?org_identifier=default");
    await page.locator("[data-test=\"add-ingestion-token\"]").click();

    const playwrightRequest0: Record<string, any> = {"name": tokenName};

    await page.getByRole("textbox", { name: "Name *" }).fill(getValue(playwrightRequest0, "name"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/**/ingestion-tokens**");
    await page.locator("[data-test=\"o-dialog-primary-btn\"]").click();
    const response0 = await responsePromise0;
    // Validate request payload
    checkRequestPayload(response0.request().postDataJSON(), expectedPayload1);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("Basic")).toContainText(expectedAuthPrefix);
    await page.getByRole("button", { name: "Copy Authorization header" }).click();
    await page.locator("[data-test=\"o-dialog-secondary-btn\"]").click();

    // The tokens table row for the newly created token shows the same Basic-encoded
    // credential (not the raw token) in its Authorization column.
    const newTokenRow = page.getByRole("row", { name: new RegExp(tokenName) });
    await expect(newTokenRow.getByRole("cell").nth(0)).toHaveText(tokenName);
    await expect(newTokenRow).toContainText(expectedAuthPrefix);

    expect(pageErrors).toHaveLength(0);
});
