// Generated by Skyramp v1.3.30 on 2026-07-08 00:07:41.045286035 +0000 UTC m=+277.809778238
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pipeline_editor_unsaved_changes_dialog.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/pipeline_editor_unsaved_changes_dialog_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(341000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on("pageerror", (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:5080/web/login");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/pipeline?org_identifier=default");
    await page.getByRole("button", { name: "New pipeline Build a flow" }).click();
    await page.locator("[data-test=\"pipeline-node-sidebar-stream-input-btn\"]").dragTo(page.getByText("Unsaved changes detected. Click \"Save\" to preserve your updates. Press enter or"));
    await page.locator("[data-test=\"input-node-stream-name-select-trigger\"]").click();
    await page.keyboard.press("Escape");
    await page.locator("[data-test=\"create-stream-toggle-btn\"]").click();
    await page.locator("[data-test=\"add-stream-name-input-field\"]").fill("testbot_pipeline_stream");
    await page.locator("[data-test=\"add-stream-save-btn\"]").click();
    await page.locator("[data-test=\"add-stream-type-input-trigger\"]").click();
    await page.getByRole("option", { name: "Logs" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/**/streams/testbot_pipeline_stream**");
    await page.locator("[data-test=\"add-stream-save-btn\"]").click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.locator("[data-test=\"app-page-header-back\"]").click();
    await expect(page.getByText("Are you sure you want to")).toHaveText("Are you sure you want to cancel changes?");
    await page.locator("[data-test=\"o-dialog-primary-btn\"]").click();
    await expect(page).toHaveURL(/\/pipeline\/pipelines(\?|$)/);
    await expect(page.getByRole("heading", { name: "Pipelines" })).toHaveText("Pipelines");

    expect(pageErrors).toHaveLength(0);
});
