// Generated by Skyramp v1.3.30 on 2026-07-08 01:27:19.680432914 +0000 UTC m=+966.203215561
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output sql-mode-clear-resets-mode.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/sql_mode_clear_resets_mode_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(205000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/logs?org_identifier=default&stream=e2e_test_logs");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.waitForLoadState('networkidle');
    await page.getByRole("textbox", { name: "Editor content" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("textbox", { name: "Editor content" }).fill("SELECT * FROM \"e2e_test_logs\" WHERE level='error'");
    await page.waitForTimeout(1000);
    const firstResponsePromise = page.waitForResponse("**/api/**/_search_stream**");
    await page.locator("[data-test=\"logs-search-bar-refresh-btn\"]").click();
    await firstResponsePromise;
    await expect(page).toHaveURL(/[?&]sql_mode=true/);

    await page.getByRole("textbox", { name: "Editor content" }).fill("");
    await page.keyboard.press("Control+a");
    await page.keyboard.press("Delete");
    const secondResponsePromise = page.waitForResponse("**/api/**/_search_stream**");
    await page.locator("[data-test=\"logs-search-bar-refresh-btn\"]").click();
    await secondResponsePromise;
    await expect(page.getByText("Showing 1 to 2 out of 2")).toContainText("Showing 1 to 2 out of 2 events", { timeout: 15000 });
    await expect(page).not.toHaveURL(/[?&]sql_mode=true/);
    expect(pageErrors).toHaveLength(0);
});
