// Generated by Skyramp v1.3.30 on 2026-07-08 01:20:36.816056106 +0000 UTC m=+563.338838764
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output sql-mode-auto-detect-false-positive.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/sql_mode_auto_detect_false_positive_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(749000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:5080/web/logs?org_identifier=default&stream=e2e_test_logs");
    await page.waitForLoadState('networkidle');
    await page.getByRole("textbox", { name: "Editor content" }).waitFor({ state: 'visible', timeout: 10000 });

    const playwrightRequest0: Record<string, any> = {"query": {"sql": "str_match(message, 'select an item from cart')"}};

    await page.getByRole("textbox", { name: "Editor content" }).fill(getValue(playwrightRequest0, "query.sql"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/**/_search_stream**");
    await page.locator("[data-test=\"logs-search-bar-refresh-btn\"]").click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // BUG: str_match(message, 'select an item from cart') is a valid filter/function
    // expression (like the sqlUtils.spec.ts case str_match(log, 'error')), not SQL.
    // Correct behavior: sql_mode must stay false and the filter should execute against
    // the stream, returning the matching event with no error banner.
    // Actual (buggy) behavior: the naive `.includes("select") && .includes("from")`
    // check in SearchBar.vue flips sql_mode=true, the text is sent to the backend as
    // literal SQL, parsing fails, and "Error occurred while retrieving search events" renders.
    await expect(page).not.toHaveURL(/[?&]sql_mode=true/);
    await expect(page.getByRole("heading", { name: "Error occurred while" })).toHaveCount(0);
    expect(response0.status()).toBeLessThan(400);
    expect(pageErrors).toHaveLength(0);
});
