// Generated by Skyramp v1.3.30 on 2026-07-07 18:06:18.2714512 +0000 UTC m=+1364.826868921
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output template_select_all_respects_prebuilt.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/template_select_all_respects_prebuilt_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/settings/templates?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.getByRole("row", { name: /prebuilt_slack/ }).waitFor({ state: "visible", timeout: 20000 });
    const customRowCount = await page.getByRole("row").filter({ hasText: "Custom" }).count();
    await page.locator("[data-test=\"o2-table-select-all\"]").getByLabel("", { exact: true }).click();
    await expect(page.getByText("selected")).toHaveText(`${customRowCount} selected`);
    await expect(page.getByRole("row", { name: /prebuilt_slack/ }).getByRole("checkbox")).toBeDisabled();
    await expect(page.getByRole("row", { name: /prebuilt_slack/ }).getByRole("checkbox")).not.toBeChecked();
    await expect(page.getByRole("row", { name: /custom_tmpl_pr12423_1/ }).getByRole("checkbox")).toBeChecked();
    expect(pageErrors).toHaveLength(0);
});
