// Generated by Skyramp v1.3.30 on 2026-07-07 18:10:00.729251788 +0000 UTC m=+1587.284669488
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output template_clone_flow.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/template_clone_flow_trace_1.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(76000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/settings/templates?org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();

    const templatePostResponsePromise = page.waitForResponse((resp) => resp.url().includes("/alerts/templates") && resp.request().method() === "POST");
    await page.locator("[data-test=\"alert-template-list-prebuilt_msteams-clone-template\"]").click();
    await page.locator("[data-test=\"add-template-submit-btn\"]").click();
    const templatePostResponse = await templatePostResponsePromise;
    expect(templatePostResponse.status()).toBe(200);

    await expect(page.getByRole("cell", { name: "Copy_of_prebuilt_msteams Custom" })).toHaveText("Copy_of_prebuilt_msteamsCustom");
    await expect(page.locator('[data-test="alert-template-list-Copy_of_prebuilt_msteams-delete-template"]')).toBeEnabled();
    expect(pageErrors).toHaveLength(0);
});
