// Generated by Skyramp v1.3.30 on 2026-07-08 00:13:57.640000072 +0000 UTC m=+559.734443972
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output trace-details-sidebar-view-logs.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/trace_details_sidebar_view_logs_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(104000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/traces/trace-details?stream=default&trace_id=5b8efff798038103d269b633813fc60c&span_id=eee19b7ec3c1b173&from=1783469144680693&to=1783472804730694&org_identifier=default");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.locator("[data-test=\"trace-details-log-streams-select-trigger\"]").click();
    await page.locator("[data-test=\"trace-details-log-streams-select-option\"]").click();
    await page.keyboard.press("Escape");
    await expect(page.locator("[data-test=\"trace-details-sidebar-header-toolbar-view-logs-btn\"]")).toBeDisabled();
    await page.locator("[data-test=\"trace-details-sidebar-header-toolbar-view-logs-btn\"]").locator("xpath=..").hover();
    await expect(page.getByRole('tooltip')).toHaveText('Select Logs stream first');
    await page.locator("[data-test=\"trace-details-log-streams-select-trigger\"]").click();
    await page.locator("[data-test=\"trace-details-log-streams-select-trigger\"]").click();
    await page.locator("[data-test=\"trace-details-log-streams-select-option\"]").click();
    await page.keyboard.press("Escape");
    await expect(page.locator("[data-test=\"trace-details-sidebar-header-toolbar-view-logs-btn\"]")).toBeEnabled();
    await page.locator("[data-test=\"trace-details-sidebar-header-toolbar-view-logs-btn\"]").click();
    await expect(page).toHaveURL(/type=trace_explorer/);
    await expect(page).toHaveURL(/query=c3Bhbl9pZD0nZWVlMTliN2VjM2MxYjE3MycgQU5EIHRyYWNlX2lkPSc1YjhlZmZmNzk4MDM4MTAzZDI2OWI2MzM4MTNmYzYwYyc/);
    expect(pageErrors).toHaveLength(0);
});
