// Generated by Skyramp v1.3.30 on 2026-07-08 00:10:52.367232944 +0000 UTC m=+374.461676865
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output trace-details-log-stream-view-logs.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/trace_details_log_stream_view_logs_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(601000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:5080/web/login");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/");
    await page.goto("http://localhost:5080/web/traces?org_identifier=default");
    await page.locator("[data-test=\"traces-no-stream-select-stream-card\"]").click();
    await page.locator("[data-test=\"log-search-index-list-select-stream-option\"]").click();
    await page.locator("[data-test=\"trace-row-service\"]").click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.locator("[data-test=\"trace-details-log-streams-select-trigger\"]").click();
    await page.keyboard.press("Escape");
    await page.goto("http://localhost:5080/web/traces/trace-details?stream=default&trace_id=5b8efff798038103d269b633813fc60c&span_id=eee19b7ec3c1b173&from=1783469144680693&to=1783472804730694&org_identifier=default");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.locator("[data-test=\"trace-details-log-streams-select-trigger\"]").click();
    await page.locator("[data-test=\"trace-details-log-streams-select-option\"]").click();
    await page.keyboard.press("Escape");
    await page.keyboard.press("Escape");
    await expect(page.locator("[data-test=\"trace-details-view-logs-btn\"]")).toBeDisabled();
    await page.locator("[data-test=\"trace-details-view-logs-btn\"]").hover();
    await expect(page.getByRole('tooltip')).toHaveText('Select Logs stream first');
    await page.locator("[data-test=\"trace-details-log-streams-select-trigger\"]").click();
    await page.locator("[data-test=\"trace-details-log-streams-select-trigger\"]").click();
    await page.locator("[data-test=\"trace-details-log-streams-select-option\"]").click();
    await page.keyboard.press("Escape");
    await expect(page.locator("[data-test=\"trace-details-view-logs-btn\"]")).toBeEnabled();
    await page.locator("[data-test=\"trace-details-view-logs-btn\"]").click();
    await expect(page).toHaveURL(/type=trace_explorer/);
    await expect(page).toHaveURL(/query=dHJhY2VfaWQ9JzViOGVmZmY3OTgwMzgxMDNkMjY5YjYzMzgxM2ZjNjBjJw/);
    expect(pageErrors).toHaveLength(0);
});
