// Generated by Skyramp v1.3.30 on 2026-07-08 06:39:13.530141085 +0000 UTC m=+1110.728911758
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output alerts-settings-additional-variables-help.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Alerts \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/alerts_settings_additional_variables_help_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(377000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:5080/web/login");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/alerts?org_identifier=default&action=add&folder=default&alert_type=all");
    await page.locator("[data-test=\"add-alert-name-input-field\"]").fill("testbot-variables-help-alert");
    await page.locator("[data-test=\"add-alert-stream-name-select-dropdown-trigger\"]").click();
    await page.locator("[data-test=\"add-alert-stream-name-select-dropdown-option\"]").click();
    await page.locator("[data-test=\"add-alert-tab-advanced\"]").click();
    await page.locator("[data-test=\"alert-variables-add-btn\"]").click();
    await page.locator("[data-test=\"alert-variables-key-input-field\"]").fill("team");
    await page.locator("[data-test=\"alert-variables-value-input-field\"]").fill("platform-oncall");
    await page.locator("[data-test=\"advanced-variables-info-btn\"]").click();
    await expect(page.getByRole("heading", { name: "Additional Variables" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Variables you've added" })).toBeVisible();
    await expect(page.locator("[data-test=\"help-your-variables\"]")).toContainText("{team}");
    await expect(page.locator("[data-test=\"help-your-variables\"]")).toContainText("platform-oncall");
    await page.locator("[data-test=\"help-builtin-toggle\"]").click();
    await expect(page.getByRole("button", { name: "{alert_description}" })).toBeVisible();
    await expect(page.getByRole("button", { name: "{alert_agg_value}" })).toHaveCount(0);
    await page.locator("[data-test=\"o-drawer-close-btn\"]").click();
    await expect(page.getByRole("heading", { name: "Additional Variables" })).not.toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
