// Generated by Skyramp v1.3.30 on 2026-07-08 06:39:17.369874495 +0000 UTC m=+1114.568645178
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output alerts-settings-row-template-help.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Alerts \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/alerts_settings_row_template_help_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(294000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:5080/web/login");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/alerts?org_identifier=default&action=add&folder=default&alert_type=all");
    await page.locator("[data-test=\"add-alert-name-input-field\"]").fill("testbot-row-template-help-alert");
    await page.locator("[data-test=\"add-alert-stream-name-select-dropdown-trigger\"]").click();
    await page.locator("[data-test=\"add-alert-stream-name-select-dropdown-option\"]").click();
    await page.locator("[data-test=\"add-alert-tab-advanced\"]").click();
    await page.locator("[data-test=\"add-alert-row-input-textarea-field\"]").fill("Host {host} logged {message}");
    await page.locator("[data-test=\"add-alert-row-input-info-btn\"]").click();
    await expect(page.getByRole("heading", { name: "Row Template", exact: true })).toBeVisible();
    await expect(page.getByRole("dialog")).toContainText("Host {host} logged {message}");
    await page.locator("[data-test=\"o-drawer-close-btn\"]").click();
    await expect(page.getByRole("heading", { name: "Row Template", exact: true })).not.toBeVisible();
    await expect(page.locator("[data-test=\"add-alert-row-input-textarea-field\"]")).toHaveValue("Host {host} logged {message}");

    expect(pageErrors).toHaveLength(0);
});
