// Generated by Skyramp v1.3.30 on 2026-07-08 06:39:08.691661051 +0000 UTC m=+1105.890431724
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output alerts-settings-template-override-preview.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Alerts \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/alerts_settings_template_override_preview_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1050000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:5080/web/login");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-password-field\"]").press("Enter");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.waitForTimeout(2000);
    await page.goto("http://localhost:5080/web/alerts?org_identifier=default");
    await page.locator("[data-test=\"alert-list-add-alert-btn\"]").click();
    await page.locator("[data-test=\"add-alert-name-input-field\"]").fill("testbot-help-drawer-alert");
    await page.locator("[data-test=\"add-alert-stream-name-select-dropdown-trigger\"]").click();
    await page.keyboard.press("Escape");
    await page.goto("http://localhost:5080/web/alerts?org_identifier=default&action=add&folder=default&alert_type=all");
    await page.goto("http://localhost:5080/web/login");
    await page.locator("[data-test=\"login-user-id-field\"]").fill("root@example.com");
    await page.locator("[data-test=\"login-password-field\"]").fill("Complexpass#123");
    await page.locator("[data-test=\"login-sign-in\"]").click();
    await page.goto("http://localhost:5080/web/alerts?org_identifier=default&action=add&folder=default&alert_type=all");
    await page.locator("[data-test=\"add-alert-name-input-field\"]").fill("testbot-help-drawer-alert");
    await page.locator("[data-test=\"add-alert-stream-name-select-dropdown-trigger\"]").click();
    await page.locator("[data-test=\"add-alert-stream-name-select-dropdown-option\"]").click();
    await page.locator("[data-test=\"alert-destinations-select-trigger\"]").click();
    await page.locator("[data-test=\"alert-destinations-select-option\"]").click();
    await page.locator("[data-test=\"add-alert-tab-advanced\"]").click();
    await page.locator("[data-test=\"advanced-template-info-btn\"]").click();
    await expect(page.getByRole("heading", { name: "Template Override" })).toBeVisible();
    await page.locator("[data-test=\"help-preview-template-select-trigger\"]").click();
    await page.getByRole("option", { name: "prebuilt_email" }).click();
    await expect(page.locator("[data-test=\"help-preview-template-select-trigger\"]")).toHaveText("prebuilt_email");
    await expect(page.locator("[data-test=\"help-apply-template-btn\"]")).toBeVisible();
    await page.locator("[data-test=\"help-apply-template-btn\"]").click();
    await expect(page.getByRole("heading", { name: "Template Override" })).not.toBeVisible();
    await expect(page.locator("[data-test=\"advanced-template-override-select\"]")).toHaveText("prebuilt_email");

    expect(pageErrors).toHaveLength(0);
});
